FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /workspace
COPY samples/pom.xml samples/pom.xml
COPY samples/src samples/src
RUN mvn -f samples/pom.xml -q package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /workspace/samples/target/producer-*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","/app/app.jar"]
